/**
 * Every spoken line in the reel, generated by tools/voices.ts (ElevenLabs) into
 * public/voices/<id>.mp3, with word timings in src/media.json.
 *
 * `text` may carry Eleven v3 delivery tags ("[deadpan]"); captions use the text
 * with tags stripped. Lines with `command` are spoken into a phone during the
 * capture and must be recognized by the real listener (Google STT) as exactly
 * that command; tools/voices.ts checks them with server/src/tools/stt-check.ts.
 */
import type { Command } from '@roadies/shared';
import type { CastId } from './cast';

/** ElevenLabs premade voices on the owner's account (swap an id to recast). */
export const VOICES = {
  narrator: 'TX3LPaxmHKxFdv7VOQHJ', // Liam: energetic social media creator (also "me", the Teal Civic)
  prius: 'onwK4e9ZLuTAKqWW03F9', // Daniel: steady British broadcaster, played deadpan
  tacoma: 'iP95p4xoKVk53GoZ742B', // Chris: charming, down-to-earth, tired dad
  miata: 'FGY2WhTYpPnrIDTdsKH5', // Laura: quirky, sassy
  mustang: 'IKne3meq5aSn9XLyUdCD', // Charlie: hyped Australian, lost in Gilroy
} as const;

export type Speaker = keyof typeof VOICES;

export interface Line {
  id: string;
  speaker: Speaker;
  text: string;
  /** Which phone speaks it during the capture; omitted = voice-over only. */
  phone?: CastId;
  /** The command the listener must hear (and nothing else for non-command phone lines). */
  command?: Command;
}

export const LINES = [
  // 1. Freeze frame
  { id: 'n-intro', speaker: 'narrator', text: "[casual] Yep. That's me. You're probably wondering how I ended up on a call with three strangers." },
  // 2. Forty minutes earlier
  { id: 'n-earlier', speaker: 'narrator', text: '[dramatic] Forty minutes earlier. [pause] I had moved... six feet.' },
  // 4. Lurking
  { id: 'prius-tuesday', speaker: 'prius', phone: 'prius', text: '[deadpan] We have not moved. Since Tuesday.' },
  { id: 'tacoma-kid', speaker: 'tacoma', phone: 'tacoma', text: '[tired] My kid just asked if we live here now.' },
  // 5. Unmute
  { id: 'hero-unmute', speaker: 'narrator', phone: 'hero', command: 'unmute', text: 'Unmute.' },
  { id: 'hero-hi', speaker: 'narrator', phone: 'hero', text: '[awkward] Hi. Teal Civic. Also not moving.' },
  { id: 'prius-hey', speaker: 'prius', phone: 'prius', text: '[deadpan] Hey.' },
  { id: 'tacoma-hey', speaker: 'tacoma', phone: 'tacoma', text: '[cheerfully] Heyyy!' },
  { id: 'miata-hey', speaker: 'miata', phone: 'miata', text: '[excited] Heyyyy!' },
  // 6. The gag: "mute" inside a sentence does nothing
  {
    id: 'miata-sushi',
    speaker: 'miata',
    phone: 'miata',
    text: "[excited] Okay, DON'T mute me, I need to tell you all about my gas station sushi.",
  },
  { id: 'prius-mute', speaker: 'prius', phone: 'prius', command: 'mute', text: 'Mute.' },
  // 8. The Prius escapes, the Mustang gets his seat
  { id: 'miata-sushi2', speaker: 'miata', phone: 'miata', text: '[excited] Okay, back to the sushi. So it was... warm?' },
  { id: 'prius-disconnect', speaker: 'prius', phone: 'prius', command: 'disconnect', text: 'Disconnect.' },
  { id: 'mustang-hello', speaker: 'mustang', phone: 'mustang', text: '[confused] ...Hello??' },
  { id: 'miata-newperson', speaker: 'miata', phone: 'miata', text: '[excited] Oh my god, new person! Okay, so the sushi—' },
  // 9. Ending
  { id: 'n-ending', speaker: 'narrator', text: "[content] Traffic didn't move once. [pause] Best commute of my life." },
  // Tail: part 2 for the nerds
  {
    id: 'n-nerds',
    speaker: 'narrator',
    text:
      "[fast] Part two, for the nerds. Every room has a hidden bot listening to every mic. Google turns what you say into commands. And mute doesn't turn your mic off. It just means only the bot can hear you. That's how it still catches unmute.",
  },
] as const satisfies readonly Line[];

export type LineId = (typeof LINES)[number]['id'];

/** Caption text: the line without Eleven v3 delivery tags. */
export const spokenText = (text: string): string =>
  text
    .replace(/\[[^\]]*\]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
