/**
 * Sound effects, generated by tools/voices.ts with ElevenLabs sound generation
 * into public/sfx/<id>.mp3. Lookalikes of meme sounds, so the reel carries
 * no licensed TikTok audio. The app's own sounds come from web/public/audio/ (copied
 * into public/gen/app-audio/ by tools/capture.ts).
 */
export interface Sfx {
  id: string;
  prompt: string;
  seconds: number;
  /** Loopable bed (ambience) rather than a one-shot. */
  loop?: boolean;
}

export const SFX = [
  { id: 'scratch', prompt: 'Vinyl record scratch, comedic freeze-frame moment, short and crisp', seconds: 1 },
  { id: 'rewind', prompt: 'VHS tape rewinding fast, warbly high-pitched rewind whirr', seconds: 1.6 },
  { id: 'boom', prompt: 'Deep cinematic bass boom hit, dramatic meme impact, short', seconds: 1.2 },
  { id: 'violin', prompt: 'Sad solo violin, short melancholy comedic phrase, slow', seconds: 3.5 },
  { id: 'whoosh', prompt: 'Fast cartoon whoosh, swoosh of something zooming past', seconds: 0.8 },
  { id: 'tick', prompt: 'Clock ticking fast, tense countdown ticks', seconds: 3 },
  { id: 'pop', prompt: 'Soft cartoon bubble pop, UI pop-in sound', seconds: 0.5 },
  { id: 'horn', prompt: 'Single short car horn honk, compact car', seconds: 0.7 },
  {
    id: 'traffic',
    prompt: 'Morning highway traffic jam ambience, idling car engines, distant car horns, no music',
    seconds: 12,
    loop: true,
  },
] as const satisfies readonly Sfx[];

export type SfxId = (typeof SFX)[number]['id'];
